export const ADDVACCINE = "VACCINE.ADDVACCINE"

export const ADDHOSPITAL = "HOSPITAL.ADDHOSPITAL"

export const ADDPATIENT = "PATIENT.ADDPATIENT"
export const SIGNIN = "PATIENT.SIGNIN"

export const ADDAPPOINTMENTS = "APPOINTMENT.ADDAPPOINTMENTS"